# Generated by Django 6.0.7 on 2026-07-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=10)),
                ('reddit_fullname', models.CharField(db_index=True, max_length=20, unique=True)),
                ('subreddit', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('permalink', models.CharField(max_length=500)),
                ('content_created_utc', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('clear', 'Clear'), ('flagged', 'Flagged')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
