# Generated by Django 6.0.7 on 2026-08-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrecord',
            name='reddit_fullname',
            field=models.CharField(db_index=True, max_length=24, unique=True),
        ),
    ]
