# Generated by Django 6.0.7 on 2026-07-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('subreddit', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('permalink', models.CharField(max_length=500)),
                ('link_id', models.CharField(max_length=20)),
                ('parent_id', models.CharField(max_length=20)),
                ('created_utc', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_utc'],
            },
        ),
        migrations.CreateModel(
            name='RawPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('subreddit', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('title', models.TextField()),
                ('selftext', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('permalink', models.CharField(max_length=500)),
                ('created_utc', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_utc'],
            },
        ),
    ]
