# Generated by Django 6.0.7 on 2026-07-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=10)),
                ('fullname', models.CharField(max_length=24)),
                ('subreddit', models.CharField(max_length=100)),
                ('permalink', models.CharField(max_length=500)),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=10)),
                ('fullname', models.CharField(db_index=True, max_length=24, unique=True)),
                ('reddit_id', models.CharField(max_length=20)),
                ('subreddit', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('permalink', models.CharField(max_length=500)),
                ('created_utc', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True)),
                ('link_id', models.CharField(blank=True, max_length=20)),
                ('parent_id', models.CharField(blank=True, max_length=20)),
                ('title', models.TextField(blank=True)),
                ('selftext', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created_utc'],
            },
        ),
    ]
