# Generated by Django 6.0.7 on 2026-08-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawitem',
            name='protect_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
