# Generated by Django 6.0.7 on 2026-07-30 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluate', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('report', 'Report')], default='report', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='unreviewed', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluate.evaluationrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
