# Generated by Django 6.0.7 on 2026-07-30 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 30, 15, 5, 42, 700252, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
