# Generated by Django 6.0.7 on 2026-08-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionrecord',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='actionrecord',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='actionrecord',
            name='reviewed_by',
        ),
    ]
