# Generated by Django 6.0.7 on 2026-07-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granularity', models.CharField(choices=[('hour', 'Hourly'), ('day', 'Daily')], max_length=5)),
                ('bucket_start', models.DateTimeField()),
                ('metric_key', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_key', 'granularity', 'bucket_start'], name='dashboard_m_metric__bde767_idx')],
                'constraints': [models.UniqueConstraint(fields=('granularity', 'bucket_start', 'metric_key'), name='unique_metric_bucket')],
            },
        ),
    ]
