"""
Django settings for red_sole_robot project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['glados', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tasks',
    'django_tasks_db',
    'ingest',
    'moderation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'red_sole_robot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'red_sole_robot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# No local Postgres is set up yet, so this defaults to SQLite for
# development. Set DATABASE_URL (e.g. postgres://user:pass@host:port/name) to
# switch to Postgres later without touching this file.

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Django Tasks — used to run AI inference as soon as an item is ingested,
# instead of on a polling interval. django-tasks-db provides the persistent,
# ORM-backed queue and the `db_worker` management command.
# https://docs.djangoproject.com/en/6.0/topics/tasks/

TASKS = {
    'default': {
        'BACKEND': 'django_tasks_db.DatabaseBackend',
    }
}


# Reddit (PRAW) ingestion

REDDIT_CLIENT_ID = env('REDDIT_CLIENT_ID', default='')
REDDIT_CLIENT_SECRET = env('REDDIT_CLIENT_SECRET', default='')
REDDIT_USERNAME = env('REDDIT_USERNAME', default='')
REDDIT_PASSWORD = env('REDDIT_PASSWORD', default='')
REDDIT_USER_AGENT = env(
    'REDDIT_USER_AGENT', default='red_sole_robot moderation assistant'
)
REDDIT_SUBREDDIT = env('REDDIT_SUBREDDIT', default='LouboutinLife')

# Raw queue caps — oldest unprocessed items beyond these are silently
# dropped by `reconcile` if inference falls behind.
QUEUE_COMMENT_CAP = env.int('QUEUE_COMMENT_CAP', default=5000)
QUEUE_POST_CAP = env.int('QUEUE_POST_CAP', default=100)

# How many recent comments/posts `reconcile` fetches from Reddit each run to
# catch anything the stream missed.
RECONCILE_COMMENT_FETCH_LIMIT = env.int(
    'RECONCILE_COMMENT_FETCH_LIMIT', default=1000
)
RECONCILE_POST_FETCH_LIMIT = env.int('RECONCILE_POST_FETCH_LIMIT', default=100)


# AI inference backend
#
# Not yet decided between Ollama / llama.cpp server / vLLM — all three can
# speak the OpenAI-compatible chat completions API, so INFERENCE_BASE_URL and
# INFERENCE_MODEL are the only settings that should need to change between
# them.
INFERENCE_BACKEND = env('INFERENCE_BACKEND', default='openai_compatible')
INFERENCE_BASE_URL = env('INFERENCE_BASE_URL', default='http://localhost:11434')
INFERENCE_MODEL = env('INFERENCE_MODEL', default='')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/red_sole_robot/static/'
