# Generated by Django 6.0.7 on 2026-07-26 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], max_length=10)),
                ('reddit_fullname', models.CharField(db_index=True, max_length=20, unique=True)),
                ('subreddit', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('permalink', models.CharField(max_length=500)),
                ('content_created_utc', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.CharField(choices=[('clear', 'Clear'), ('flagged', 'Flagged')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('reddit_report_submitted', models.BooleanField(default=False)),
                ('reddit_report_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reddit_report_error', models.CharField(blank=True, max_length=500)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='unreviewed', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
